<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210728045656 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE dtb_customer DROP vt4g_account_id, CHANGE customer_status_id customer_status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE sex_id sex_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE job_id job_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT NULL, CHANGE kana02 kana02 VARCHAR(255) DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(8) DEFAULT NULL, CHANGE addr01 addr01 VARCHAR(255) DEFAULT NULL, CHANGE addr02 addr02 VARCHAR(255) DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(14) DEFAULT NULL, CHANGE birth birth DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE first_buy_date first_buy_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE last_buy_date last_buy_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE note note VARCHAR(4000) DEFAULT NULL, CHANGE reset_key reset_key VARCHAR(255) DEFAULT NULL, CHANGE reset_expire reset_expire DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\'');
        $this->addSql('ALTER TABLE dtb_product ADD specifics VARCHAR(255) DEFAULT NULL, ADD limit_count VARCHAR(255) DEFAULT NULL, DROP `specific`, DROP `limit`, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE product_status_id product_status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE note note VARCHAR(4000) DEFAULT NULL, CHANGE description_list description_list VARCHAR(4000) DEFAULT NULL, CHANGE description_detail description_detail VARCHAR(4000) DEFAULT NULL, CHANGE search_word search_word VARCHAR(4000) DEFAULT NULL, CHANGE premium premium VARCHAR(255) DEFAULT NULL, CHANGE niconico niconico VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_base_info CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE company_kana company_kana VARCHAR(255) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(8) DEFAULT NULL, CHANGE addr01 addr01 VARCHAR(255) DEFAULT NULL, CHANGE addr02 addr02 VARCHAR(255) DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(14) DEFAULT NULL, CHANGE business_hour business_hour VARCHAR(255) DEFAULT NULL, CHANGE email01 email01 VARCHAR(255) DEFAULT NULL, CHANGE email02 email02 VARCHAR(255) DEFAULT NULL, CHANGE email03 email03 VARCHAR(255) DEFAULT NULL, CHANGE email04 email04 VARCHAR(255) DEFAULT NULL, CHANGE shop_name shop_name VARCHAR(255) DEFAULT NULL, CHANGE shop_kana shop_kana VARCHAR(255) DEFAULT NULL, CHANGE shop_name_eng shop_name_eng VARCHAR(255) DEFAULT NULL, CHANGE good_traded good_traded VARCHAR(4000) DEFAULT NULL, CHANGE message message VARCHAR(4000) DEFAULT NULL, CHANGE delivery_free_amount delivery_free_amount NUMERIC(12, 2) UNSIGNED DEFAULT NULL, CHANGE delivery_free_quantity delivery_free_quantity INT UNSIGNED DEFAULT NULL, CHANGE authentication_key authentication_key VARCHAR(255) DEFAULT NULL, CHANGE php_path php_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_authority_role CHANGE authority_id authority_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_block CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE block_name block_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_block_position CHANGE block_row block_row INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_cart CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE cart_key cart_key VARCHAR(255) DEFAULT NULL, CHANGE pre_order_id pre_order_id VARCHAR(255) DEFAULT NULL, CHANGE sort_no sort_no SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_cart_item CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE cart_id cart_id INT UNSIGNED DEFAULT NULL, CHANGE point_rate point_rate NUMERIC(10, 0) UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_category CHANGE parent_category_id parent_category_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_class_category CHANGE class_name_id class_name_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE backend_name backend_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_class_name CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE backend_name backend_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_csv CHANGE csv_type_id csv_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE reference_field_name reference_field_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_customer_address CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT NULL, CHANGE kana02 kana02 VARCHAR(255) DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(8) DEFAULT NULL, CHANGE addr01 addr01 VARCHAR(255) DEFAULT NULL, CHANGE addr02 addr02 VARCHAR(255) DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(14) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_customer_favorite_product CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE product_id product_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE sale_type_id sale_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE service_name service_name VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(4000) DEFAULT NULL, CHANGE confirm_url confirm_url VARCHAR(4000) DEFAULT NULL, CHANGE sort_no sort_no INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery_duration CHANGE name name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery_fee CHANGE delivery_id delivery_id INT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery_time CHANGE delivery_id delivery_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_layout CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE layout_name layout_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_mail_history CHANGE order_id order_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE send_date send_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE mail_subject mail_subject VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_mail_template CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE file_name file_name VARCHAR(255) DEFAULT NULL, CHANGE mail_subject mail_subject VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_member CHANGE work_id work_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE authority_id authority_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE department department VARCHAR(255) DEFAULT NULL, CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE login_date login_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\'');
        $this->addSql('ALTER TABLE dtb_news CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE publish_date publish_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE url url VARCHAR(4000) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_order CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE sex_id sex_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE job_id job_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE payment_id payment_id INT UNSIGNED DEFAULT NULL, CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pre_order_id pre_order_id VARCHAR(255) DEFAULT NULL, CHANGE order_no order_no VARCHAR(255) DEFAULT NULL, CHANGE message message VARCHAR(4000) DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT NULL, CHANGE kana02 kana02 VARCHAR(255) DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(14) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(8) DEFAULT NULL, CHANGE addr01 addr01 VARCHAR(255) DEFAULT NULL, CHANGE addr02 addr02 VARCHAR(255) DEFAULT NULL, CHANGE birth birth DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE payment_method payment_method VARCHAR(255) DEFAULT NULL, CHANGE note note VARCHAR(4000) DEFAULT NULL, CHANGE order_date order_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE payment_date payment_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE currency_code currency_code VARCHAR(255) DEFAULT NULL, CHANGE order_status_id order_status_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_order_item CHANGE order_id order_id INT UNSIGNED DEFAULT NULL, CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE shipping_id shipping_id INT UNSIGNED DEFAULT NULL, CHANGE rounding_type_id rounding_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE tax_type_id tax_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE tax_display_type_id tax_display_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE order_item_type_id order_item_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE product_code product_code VARCHAR(255) DEFAULT NULL, CHANGE class_name1 class_name1 VARCHAR(255) DEFAULT NULL, CHANGE class_name2 class_name2 VARCHAR(255) DEFAULT NULL, CHANGE class_category_name1 class_category_name1 VARCHAR(255) DEFAULT NULL, CHANGE class_category_name2 class_category_name2 VARCHAR(255) DEFAULT NULL, CHANGE tax_rule_id tax_rule_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency_code currency_code VARCHAR(255) DEFAULT NULL, CHANGE processor_name processor_name VARCHAR(255) DEFAULT NULL, CHANGE point_rate point_rate NUMERIC(10, 0) UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_order_pdf CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE message1 message1 VARCHAR(255) DEFAULT NULL, CHANGE message2 message2 VARCHAR(255) DEFAULT NULL, CHANGE message3 message3 VARCHAR(255) DEFAULT NULL, CHANGE note1 note1 VARCHAR(255) DEFAULT NULL, CHANGE note2 note2 VARCHAR(255) DEFAULT NULL, CHANGE note3 note3 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_page CHANGE master_page_id master_page_id INT UNSIGNED DEFAULT NULL, CHANGE page_name page_name VARCHAR(255) DEFAULT NULL, CHANGE file_name file_name VARCHAR(255) DEFAULT NULL, CHANGE author author VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE keyword keyword VARCHAR(255) DEFAULT NULL, CHANGE meta_robots meta_robots VARCHAR(255) DEFAULT NULL, CHANGE meta_tags meta_tags VARCHAR(4000) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_payment CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE payment_method payment_method VARCHAR(255) DEFAULT NULL, CHANGE rule_max rule_max NUMERIC(12, 2) UNSIGNED DEFAULT NULL, CHANGE sort_no sort_no SMALLINT UNSIGNED DEFAULT NULL, CHANGE payment_image payment_image VARCHAR(255) DEFAULT NULL, CHANGE rule_min rule_min NUMERIC(12, 2) UNSIGNED DEFAULT NULL, CHANGE method_class method_class VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_product_class CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE sale_type_id sale_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE class_category_id1 class_category_id1 INT UNSIGNED DEFAULT NULL, CHANGE class_category_id2 class_category_id2 INT UNSIGNED DEFAULT NULL, CHANGE delivery_duration_id delivery_duration_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE product_code product_code VARCHAR(255) DEFAULT NULL, CHANGE stock stock NUMERIC(10, 0) DEFAULT NULL, CHANGE sale_limit sale_limit NUMERIC(10, 0) UNSIGNED DEFAULT NULL, CHANGE price01 price01 NUMERIC(12, 2) DEFAULT NULL, CHANGE delivery_fee delivery_fee NUMERIC(12, 2) UNSIGNED DEFAULT NULL, CHANGE currency_code currency_code VARCHAR(255) DEFAULT NULL, CHANGE point_rate point_rate NUMERIC(10, 0) UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_product_image CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_product_stock CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE stock stock NUMERIC(10, 0) DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_product_tag CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE tag_id tag_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_shipping CHANGE order_id order_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE delivery_id delivery_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT NULL, CHANGE kana02 kana02 VARCHAR(255) DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(14) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(8) DEFAULT NULL, CHANGE addr01 addr01 VARCHAR(255) DEFAULT NULL, CHANGE addr02 addr02 VARCHAR(255) DEFAULT NULL, CHANGE delivery_name delivery_name VARCHAR(255) DEFAULT NULL, CHANGE time_id time_id INT UNSIGNED DEFAULT NULL, CHANGE delivery_time delivery_time VARCHAR(255) DEFAULT NULL, CHANGE delivery_date delivery_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE shipping_date shipping_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\', CHANGE tracking_number tracking_number VARCHAR(255) DEFAULT NULL, CHANGE note note VARCHAR(4000) DEFAULT NULL, CHANGE sort_no sort_no SMALLINT UNSIGNED DEFAULT NULL, CHANGE mail_send_date mail_send_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetimetz)\'');
        $this->addSql('ALTER TABLE dtb_tax_rule CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE rounding_type_id rounding_type_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_template CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE plg_blog_data CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE blog_status_id blog_status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE author author VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE keyword keyword VARCHAR(255) DEFAULT NULL, CHANGE meta_robots meta_robots VARCHAR(255) DEFAULT NULL, CHANGE release_date release_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE plg_blog_image CHANGE blog_id blog_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE plg_blog_category CHANGE class class VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE plg_blog_config CHANGE title_en title_en VARCHAR(255) DEFAULT \'Blog\' NOT NULL, CHANGE title_jp title_jp VARCHAR(255) DEFAULT \'ブログ\' NOT NULL');
        $this->addSql('ALTER TABLE plg_lottery_probability_config CHANGE rank_name rank_name VARCHAR(255) NOT NULL, CHANGE explain_text explain_text VARCHAR(255) NOT NULL, CHANGE display_winning display_winning VARCHAR(255) NOT NULL, CHANGE color color VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE plg_prize_show_config CHANGE image image VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE plg_sort_product CHANGE sort_no sort_no INT DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE dtb_authority_role CHANGE authority_id authority_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_base_info CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE company_name company_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE company_kana company_kana VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE postal_code postal_code VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr01 addr01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr02 addr02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE phone_number phone_number VARCHAR(14) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE business_hour business_hour VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE email01 email01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE email02 email02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE email03 email03 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE email04 email04 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE shop_name shop_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE shop_kana shop_kana VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE shop_name_eng shop_name_eng VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE good_traded good_traded VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE message message VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE delivery_free_amount delivery_free_amount NUMERIC(12, 2) UNSIGNED DEFAULT \'NULL\', CHANGE delivery_free_quantity delivery_free_quantity INT UNSIGNED DEFAULT NULL, CHANGE authentication_key authentication_key VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE php_path php_path VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_block CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE block_name block_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_block_position CHANGE block_row block_row INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_cart CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE cart_key cart_key VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE pre_order_id pre_order_id VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE sort_no sort_no SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_cart_item CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE cart_id cart_id INT UNSIGNED DEFAULT NULL, CHANGE point_rate point_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE dtb_category CHANGE parent_category_id parent_category_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_class_category CHANGE class_name_id class_name_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE backend_name backend_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_class_name CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE backend_name backend_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_csv CHANGE csv_type_id csv_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE reference_field_name reference_field_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_customer ADD vt4g_account_id VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE customer_status_id customer_status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE sex_id sex_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE job_id job_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE kana02 kana02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE company_name company_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE postal_code postal_code VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr01 addr01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr02 addr02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE phone_number phone_number VARCHAR(14) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE birth birth DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE salt salt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE first_buy_date first_buy_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE last_buy_date last_buy_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE note note VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE reset_key reset_key VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE reset_expire reset_expire DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\'');
        $this->addSql('ALTER TABLE dtb_customer_address CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE kana02 kana02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE company_name company_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE postal_code postal_code VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr01 addr01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr02 addr02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE phone_number phone_number VARCHAR(14) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_customer_favorite_product CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE product_id product_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE sale_type_id sale_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE service_name service_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE description description VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE confirm_url confirm_url VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE sort_no sort_no INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery_duration CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_delivery_fee CHANGE delivery_id delivery_id INT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_delivery_time CHANGE delivery_id delivery_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_layout CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE layout_name layout_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_mail_history CHANGE order_id order_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE send_date send_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE mail_subject mail_subject VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_mail_template CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE file_name file_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE mail_subject mail_subject VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_member CHANGE work_id work_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE authority_id authority_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE department department VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE salt salt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE login_date login_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\'');
        $this->addSql('ALTER TABLE dtb_news CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE publish_date publish_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE url url VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_order CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE sex_id sex_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE job_id job_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE payment_id payment_id INT UNSIGNED DEFAULT NULL, CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pre_order_id pre_order_id VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE order_no order_no VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE message message VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE kana01 kana01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE kana02 kana02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE company_name company_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE email email VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE phone_number phone_number VARCHAR(14) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE postal_code postal_code VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr01 addr01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr02 addr02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE birth birth DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE payment_method payment_method VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE note note VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE order_date order_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE payment_date payment_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE currency_code currency_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE order_status_id order_status_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_order_item CHANGE order_id order_id INT UNSIGNED DEFAULT NULL, CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE shipping_id shipping_id INT UNSIGNED DEFAULT NULL, CHANGE rounding_type_id rounding_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE tax_type_id tax_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE tax_display_type_id tax_display_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE order_item_type_id order_item_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE product_code product_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE class_name1 class_name1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE class_name2 class_name2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE class_category_name1 class_category_name1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE class_category_name2 class_category_name2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE tax_rule_id tax_rule_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency_code currency_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE processor_name processor_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE point_rate point_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE dtb_order_pdf CHANGE title title VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE message1 message1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE message2 message2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE message3 message3 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE note1 note1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE note2 note2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE note3 note3 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_page CHANGE master_page_id master_page_id INT UNSIGNED DEFAULT NULL, CHANGE page_name page_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE file_name file_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE author author VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE keyword keyword VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE meta_robots meta_robots VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE meta_tags meta_tags VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_payment CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE payment_method payment_method VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE rule_max rule_max NUMERIC(12, 2) UNSIGNED DEFAULT \'NULL\', CHANGE sort_no sort_no SMALLINT UNSIGNED DEFAULT NULL, CHANGE payment_image payment_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE rule_min rule_min NUMERIC(12, 2) UNSIGNED DEFAULT \'NULL\', CHANGE method_class method_class VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_product ADD `specifics` VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, ADD `limit_count` VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, DROP specific, DROP limit, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE product_status_id product_status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE note note VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE description_list description_list VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE description_detail description_detail VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE search_word search_word VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE premium premium VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE niconico niconico VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE dtb_product_class CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE sale_type_id sale_type_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE class_category_id1 class_category_id1 INT UNSIGNED DEFAULT NULL, CHANGE class_category_id2 class_category_id2 INT UNSIGNED DEFAULT NULL, CHANGE delivery_duration_id delivery_duration_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE product_code product_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE stock stock NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE sale_limit sale_limit NUMERIC(10, 0) UNSIGNED DEFAULT \'NULL\', CHANGE price01 price01 NUMERIC(12, 2) DEFAULT \'NULL\', CHANGE delivery_fee delivery_fee NUMERIC(12, 2) UNSIGNED DEFAULT \'NULL\', CHANGE currency_code currency_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE point_rate point_rate NUMERIC(10, 0) UNSIGNED DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE dtb_product_image CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_product_stock CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE stock stock NUMERIC(10, 0) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE dtb_product_tag CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE tag_id tag_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_shipping CHANGE order_id order_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE delivery_id delivery_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE kana01 kana01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE kana02 kana02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE company_name company_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE phone_number phone_number VARCHAR(14) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE postal_code postal_code VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr01 addr01 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE addr02 addr02 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE delivery_name delivery_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE time_id time_id INT UNSIGNED DEFAULT NULL, CHANGE delivery_time delivery_time VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE delivery_date delivery_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE shipping_date shipping_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\', CHANGE tracking_number tracking_number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE note note VARCHAR(4000) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE sort_no sort_no SMALLINT UNSIGNED DEFAULT NULL, CHANGE mail_send_date mail_send_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetimetz)\'');
        $this->addSql('ALTER TABLE dtb_tax_rule CHANGE product_class_id product_class_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE country_id country_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE pref_id pref_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE product_id product_id INT UNSIGNED DEFAULT NULL, CHANGE rounding_type_id rounding_type_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE dtb_template CHANGE device_type_id device_type_id SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE plg_blog_category CHANGE class class VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE plg_blog_config CHANGE title_en title_en VARCHAR(255) DEFAULT \'\'Blog\'\' NOT NULL COLLATE utf8_general_ci, CHANGE title_jp title_jp VARCHAR(255) DEFAULT \'\'ブログ\'\' NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE plg_blog_data CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL, CHANGE blog_status_id blog_status_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE author author VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE keyword keyword VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE meta_robots meta_robots VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_general_ci, CHANGE release_date release_date DATETIME DEFAULT \'NULL\' COMMENT \'(DC2Type:datetime)\'');
        $this->addSql('ALTER TABLE plg_blog_image CHANGE blog_id blog_id INT UNSIGNED DEFAULT NULL, CHANGE creator_id creator_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE plg_lottery_probability_config CHANGE rank_name rank_name VARCHAR(255) NOT NULL COLLATE utf8_general_ci, CHANGE explain_text explain_text VARCHAR(255) NOT NULL COLLATE utf8_general_ci, CHANGE display_winning display_winning VARCHAR(255) NOT NULL COLLATE utf8_general_ci, CHANGE color color VARCHAR(255) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE plg_prize_show_config CHANGE image image VARCHAR(255) NOT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE plg_sort_product CHANGE sort_no sort_no INT DEFAULT NULL');
    }
}
